src/main/java/com/devcourse/eggmarket/domain/model/image/Image.java, src/main/java/com/devcourse/eggmarket/domain/model/image/LocalImageUpload.java, src/main/java/com/devcourse/eggmarket/domain/model/image/PostImage.java, src/main/java/com/devcourse/eggmarket/domain/model/image/ProfileImage.java
- InputStream is closed 으로 인한 에러 발생하여 byte[] 를 사용하여 메모리에 일시적으로 저장하는 방식을 택하였음
- 기존 이슈 : Inputstream is closed 로 인한 예외 발생
- EM-57
=> 🐛 fix : Image 에서 InputStream 이 아닌 byte[] 를 사용하여 이미지 컨텐츠 저장하는 방식으로 변경

scripts/start.sh, scripts/stop.sh
- 변수명을 잘못 비교하여 애플리케이션이 정상적으로 종료되지 않는 현상이 발생
- 종료 쉘 스크립트의 변수명 수정하여 해결
- 현재 프로세스 체크를 프로젝트 이름으로만 하도록 변경
- [EM-41](https://hkasdasdq.atlassian.net/browse/EM-41)
=> 🐛 fix : 배포중 프로세스가 종료되지 않는 현상 수정

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostRequest.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/PostExceptionMessage.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/main/java/com/devcourse/eggmarket/global/common/ValueOfEnum.java, src/main/java/com/devcourse/eggmarket/global/common/ValueOfEnumValidator.java, src/test/java/com/devcourse/eggmarket/domain/post/converter/PostConverterTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java
- 로그인한 사용자에 한해서 판매글을 작성할 수 있는 기능 추가
- 전달받은 값이 enum에 존재하는지 확인하는 커스텀 어노테이션 구현
- DTO -> entity 변환 기능 구현
- 테스트 코드 추가(컨트롤러 제외)
- [EM-18](https://hkasdasdq.atlassian.net/browse/EM-18)
- 테스트 코드에서 Authentication을 받아오지 못해(null) 계속 에러 발생
- Postman을 통해서 기능은 잘 돌아가는 것은 확인했으나 인증정보를 mocking 하는 방법을 구현하는데 너무 오래걸릴 것 같아 일단 스킵
=> ✨ feat : 판매글 작성 기능 추가

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/NotExistPostException.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/NotMatchedSellerException.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/PostExceptionMessage.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java, src/test/java/com/devcourse/eggmarket/domain/stub/UserStub.java
- 판매글 내용을 업데이트할 수 있는 기능 추가
- 업데이트시 발생할 수 있는 커스텀 exception 추가
- 판매글 업데이트 관련 테스트 코드 추가 (TODO 존재)
- 판매글 테스트시 사용하는 stub 추가
- [EM-19](https://hkasdasdq.atlassian.net/browse/EM-19)
- 엔티티의 ID 값이 실제로 증가하지 않아 null 들어가서 테스트를 어떻게 작성할지 해결하지 못했습니다. 이와 관련해서 해결방법을 아는 분은 공유 부탁드립니다.
- 테스트가 어려운 부분의 위에 TODO로 표시해 두었습니다.
=> ✨ feat : 판매글 내용 업데이트 기능 추가

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- 판매글의 정보를 변경할때는 `/posts/{id}/post` 판매글의 상태를 변경할 때는 `/posts/{id}/purchase` 로 변경하도록 수정
- 판매자와 로그인 유저가 다를 경우 예외 발생
- 판매글 상태는 구매자와 판매상태만 입력받아 수정하도록 구현
- [EM-61](https://hkasdasdq.atlassian.net/browse/EM-61)
- id 값 mocking 문제로 인한 테스트 코드 작성 보류
=> ✨ feat : 판매글 상태변경 기능 추가

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostResponse.java, src/main/java/com/devcourse/eggmarket/domain/post/model/Post.java, src/main/java/com/devcourse/eggmarket/domain/post/model/PostAttention.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostAttentionRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/DefaultPostAttentionService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostAttentionService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/converter/PostConverterTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostAttentionRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java
- 💥  Post 생성자에 Long id 를 인자로 받도록 변경하였습니다 💥 
- 💥  PostResponse 를 아우터 클래스로 변경
- SinglePost
- PostLikeCount 등 여러개의 응답 객체 필요성으로 인해 아우터 클래스로변경함
- 포스트 단일 응답 객체 의 필드 변경
- sellerId, buyerId 삭제
- 추후 : buyer 포함(?)
- UserResponse 추가
- likeCount 추가
- commentCount 추가 (Converter 에서 일단 무조건 0 이 들어오게 세팅)
- imgPath List 추가 (일단 EmptyCollection 들어오게 세팅)
- 관심 버튼을 누르면 해당 게시글에 대한, 로그인한 사용자의 관심 여부가 반대로 변경되도록 하는 기능 추가
- posts/{id}/attention + POST METHOD 를 통해, 현재 로그인 사용자는 해당 게시글에 대한 "관심" 여부를 변경할 수 있다 
- 관심 버튼을 누르면, 결과로 "관심 개수" 가 리턴된다
-  seller 는 POST와의 연관관계를 EAGER 로 하기로 했었는데, buyer 는 LAZY 로 하기로 했던 것 같습니다 . 그런데 현재 buyer 와의 관계도 EAGER 로 되어있는 것을 확인하였습니다. 
- PostImage "엔티티" 추가  예정입니다.
- --- 이에 따라 Post write 관련 기존 로직에 변경될 예정입니다! Post 도 당연히 변경될 예정입니다(용철님 작성부분)💥
- --- 기존의 Image 인터페이스를 -> ImageFile 이라는 네이밍으로 변경할 예정입니다! 이로 …
=> ✨ feat : 판매글 관심여부 변경 기능 추가

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostResponse.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/DefaultPostAttentionService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostAttentionService.java, src/test/java/com/devcourse/eggmarket/domain/post/converter/PostConverterTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java
- PostAttentionRepository 에, 특정 사용자가 관심목록으로 추가한 판매글들을 불러오는 쿼리 추가 ( 페이징은 구현 ❌ )
- 판매글 응답 DTO 추가 와 그에 따른 컨버터 메소드 추가 및 테스트 추가
- 판매글 "목록" 을 불러올 때 판매글에 포함되어야 할 데이터와 "판매글만 단일조회할 때 데이터" 는 다르다는 판단하에 별도의 DTO 를작성
- PostsElement
- 판매글 목록에 대해 Posts 라는 응답으로 List 형태로 반환 하도록 하였음
- Posts
- 🔆 후에 Paging 과 관련하여 생각하시는게 있다면, 이 부분이 변경될 수 있다고 생각합니다. 저는 아직 Paging 관련 작성을 고려하지 않아 이렇게 작성하였습니다
- 관심목록에 "추가" 하는 테스트와 "삭제" 하는 테스트를 별도로 작성하여 추가함
- EM-62
=> ✨ feat : 로그인 사용자의 관심목록 불러오기 기능 추가

src/main/java/com/devcourse/eggmarket/domain/model/image/ImageFile.java, src/main/java/com/devcourse/eggmarket/domain/model/image/ImageUpload.java, src/main/java/com/devcourse/eggmarket/domain/model/image/LocalImageUpload.java, src/main/java/com/devcourse/eggmarket/domain/model/image/PostImageFile.java, src/main/java/com/devcourse/eggmarket/domain/model/image/ProfileImageFile.java, src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostRequest.java, src/main/java/com/devcourse/eggmarket/domain/post/model/PostImage.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostImageRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/main/java/com/devcourse/eggmarket/domain/user/converter/UserConverter.java, src/main/java/com/devcourse/eggmarket/domain/user/service/DefaultUserService.java, src/test/java/com/devcourse/eggmarket/domain/model/image/LocalImageUploadTest.java, src/test/java/com/devcourse/eggmarket/domain/model/image/PostImageFileTest.java, src/test/java/com/devcourse/eggmarket/domain/post/converter/PostConverterTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostImageRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- Image 인터페이스 및 Image 구현체들 이름 변경 -> ImageFile
- PostImage 엔티티 추가 
- PostImageRepository 추가
- form-data 를 통한 요청만을 받기 때문에, @ResponseBody 를 제거하였습니다
- 판매글 작성 로직 변경 (이미지 업로드를 추가하였음)
- PostServiceImpl 에서 private 메소드의 위치는 아래쪽으로 이동시켰습니다 ( 코드컨벤션)
- 이미지 업로드시 postid_순서  라는 이름으로 저장하다보니, 순차적으로 증가하는 순서가 필요하여 Order 객체를 정의하여 사용하였습니다
- 이미지 파일 크기 초과에 따른 오류는 servlet 단에서 발생하여, 예외처리에 대한 어려움을 느끼고 있습니다. 해당 예외는 GlobalExceptionHandler 에서 바로 잡아서 처리하는 것으로 해도 되는지에 대해 의논이 필요합니다 
- EM-56
=> ✨ feat: 판매글 작성시 이미지 업로드 기능 추가

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java
- url query를 통해 카테고리를 지정하여 해당 카테고리만 검색되도록 구현
- 테스트 코드 작성
- EM-24
- 카테고리를 넣어도 안넣어도 상관없게 하기 위해 optional을 사용했는데 이로인해 이전에 사용하던 Enum 체크 방식을 사용하기 힘들어졌습니다. (Optional로 묶여 있기 때문에)
그래서 현재 Validation에서 발생하지 않고 Jackson에서 Mapping 실패하는 예외로 발생합니다.
=> ✨ feat : 판매글을 카테고리로 페이지 조회 기능 추가

docs/post-api.adoc, src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostRequest.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/PostExceptionMessage.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- 판매글 작성시 valid check를 @ParameterizedTest를 사용하여 구현하도록 수정
- 판매글 본문과 상태변경 수정하는 컨트롤러 계층 테스트 코드 추가
- 컨트롤러에서 @Valid 적용
- restdocs에 판매글 수정 관련 추가
- EM-18, EM-19
=> 🧪 test : 판매글 수정 관련 컨트롤러 테스트 코드 작성

docs/post-api.adoc, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java
- 컨트롤러 계층에서 판매글 삭제시 테스트 코드 추가
- restdoc에 판매글 삭제 부분 추가
- EM-20
=> 🧪 test : 판매글 삭제 컨트롤러 테스트 추가

src/main/java/com/devcourse/eggmarket/domain/comment/api/CommentController.java, src/main/java/com/devcourse/eggmarket/domain/comment/dto/CommentRequest.java, src/main/java/com/devcourse/eggmarket/domain/comment/dto/CommentResponse.java, src/main/java/com/devcourse/eggmarket/domain/comment/exception/NotExistCommentException.java, src/main/java/com/devcourse/eggmarket/domain/comment/exception/NotWriterException.java, src/main/java/com/devcourse/eggmarket/domain/comment/model/Comment.java, src/main/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepository.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/CommentService.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/DefaultCommentService.java, src/main/java/com/devcourse/eggmarket/global/error/ErrorField.java, src/main/java/com/devcourse/eggmarket/global/error/ErrorMessage.java, src/main/java/com/devcourse/eggmarket/global/error/ErrorResponse.java, src/main/java/com/devcourse/eggmarket/global/error/GlobalExceptionHandler.java, src/main/java/com/devcourse/eggmarket/global/error/exception/ErrorCode.java, src/test/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/comment/service/CommentServiceIntegrationTest.java
- 예외 발생 시, 기존에는 아래와 같은 모습
```json
{
"code": "G03",
"message": "서버 에러 입니다"
}
```
```java
{
"code": "G01",
"message": "org.springframework.validation.BeanPropertyBindingResult: 2 errors\nField error in object 'save' on field 'category': rejected value [BEAUT]; codes [ValueOfEnum.save.category,ValueOfEnum.category,ValueOfEnum.java.lang.String,ValueOfEnum]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [save.category,category]; arguments []; default message [category],class com.devcourse.eggmarket.domain.post.model.Category]; default message [잘못 된 카테고리 입니다]\nField error in object 'save' on field 'price': rejected value [-1]; codes [PositiveOrZero.save.price,PositiveOrZero.price,PositiveOrZero.int,PositiveOrZero]; arguments …
```
=> ♻️  refactor : 에러상황에 대한 응답 객체 재정의 및 하위 에러 객체 정의 및 구현 

docs/post-api.adoc, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- 판매글 단일 조회 컨트롤러 계층 테스트 작성
- 판매글 단일 조회 restdocs 적용
- EM-43
=> 🧪 test : 판매글 단일 조회 테스트 작성

src/main/java/com/devcourse/eggmarket/domain/comment/api/CommentController.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/DefaultCommentService.java, src/test/java/com/devcourse/eggmarket/domain/comment/service/CommentServiceIntegrationTest.java
- 댓글 삭제 기능 구현 ( 컨트롤러, 서비스)
- 댓글 삭제 기능 서비스 테스트 (기능 테스트) 추가
- 댓글 컨트롤러 클래스레벨에 RequestMapping("posts/{postId}") 추가
- EM-28
=> ✨ feat : 댓글 삭제 기능 구현 및 서비스 테스트 구현

src/main/asciidoc/post-api.adoc, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java
- 판매글 조회 restdocs 출력 내용 수정 (id -> data.posts[].id)
- 판매글을 특정 카테고리 기준으로 조회에 대한 테스트 코드 작성
- 판매글 카테고리 조회 restdocs 추가
- EM-24
=> 🧪 test : 판매글 카테고리 조회 테스트 추가

.github/workflows/maven.yml, src/main/resources/logback.xml
- 로그 생성시 생성하는 폴더의 권한이 낮아 (일반유저로 `/`에 만들려고 시도) 실행 후 계속 에러 발생으로 꺼지는 현상이 발생
- `/var/log/egg-market` 이라는 폴더를 만들고 해당 폴더에 일반 유저 권한을 갖도록 수정
- logback으로 로깅한 내용은 `/var/log/egg-market` 으로 저장하도록 수정
- EM-50
=> 🔧 config : 배포시 유저 권한 문제로 인한 로그백 에러 발생에 대한 처리

src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/ImageStub.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- 판매글 단일 조회시 업로드했던 이미지도 같이 불러오는 기능 추가(이미지 경로로 전달)
- 판매글 단일 조회 테스트 코드 추가(유닛, 통합)
-  EM-43
- 값을 전체 비교하도록 구현했다가 ID만 구현하도록 변경
- 로컬에서는 테스트가 통과하지만 github actions 환경(ubuntu)에서 createAt(생성시간)의 시간에 사소한 차이가 있어 예외발생(get으로 불러올때 소수가 더길게나옴) 이때문에 ID만 비교하도록 변경함
=> ✨ feat : 판매글 단일 조회시 이미지 불러오기 기능 추가

src/main/java/com/devcourse/eggmarket/domain/model/image/PostImageFile.java, src/main/java/com/devcourse/eggmarket/domain/model/image/ProfileImageFile.java, src/test/java/com/devcourse/eggmarket/domain/model/ProfileImageFileTest.java
- 기존에 하드코딩된 파일 세퍼레이터로 인해 플랫폼이 달라지면 유효한 이미지 생성경로가 생성되지 않는 문제가 존재하여 이를 해결하고자 하였습니다
- PostImageFile 클래스에서 처럼 apache commons 라이브러리를 사용하여 플랫폼 의존적이지 않은 파일업로드 경로를 생성하도록 하였습니다
- EM-75
=> 🐛 fix : 프로필 이미지 업로드 경로 생성로직 수정 및 테스트코드 추가

pom.xml, src/main/java/com/devcourse/eggmarket/domain/comment/model/Comment.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/model/Evaluation.java, src/main/java/com/devcourse/eggmarket/domain/post/model/Post.java, src/main/java/com/devcourse/eggmarket/domain/post/model/PostAttention.java, src/main/java/com/devcourse/eggmarket/domain/post/model/PostImage.java, src/main/java/com/devcourse/eggmarket/domain/user/model/User.java, src/main/resources/application-local.yaml, src/main/resources/application-prod.yaml, src/main/resources/schema.sql, src/test/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepositoryTest.java
- 기본키 생성전략을 IDENTITY 로 변경
- 스키마 스크립트를 사용하기 위해 yaml 의 hibernate 의 ddl-auto 를 제거 
fk 들에 대해 이름을 직접 명시해두어서 아래와 같습니다
- 프로필 별로 설정을 다르게 할 것인지에 대해 고민됩니다. local 만을 사용해오던 상황이라, 기존의 local 에 설정을 그대로 변경하였는데, 이에 대한 고민이 존재합니다 
- flyway 잔재가 남아있슴다
- EM-46
=> ✨  feat : 스키마 DDL 스크립트 추가 및 yaml 설정 

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostImageRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/DefaultPostAttentionService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostAttentionService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/main/java/com/devcourse/eggmarket/domain/user/controller/UserController.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostImageRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java
- 관심 목록을 가져올 때, 포스트의 썸네일 이미지 경로를 가져오지 않고 있었어서 이를 추가하였습니다.
- 기존에 람다내 공유변수 변경 불가 제약으로 정의했던 Order 클래스를 제거하고 AtomicInteger 를 사용하였습니다. 
- 기존에 썸네일 추가 로직에 null 초기화 변수가 존재하여 null 초기화를 제거하기 위한 리팩토링을 하였습니다.
- multipart form 형식으로 요청을 받는 핸들러 메소드에는 명시적으로 consume 으로 해당 미디어 타입을 받는 것으로 하였습니다 
- 관심 목록 을 가져오는 기능은 판매글 목록을 가져오는 서비스들 중 하나로 판단되어 PostService 로 책임을 변경하였습니다. 덕분에 썸네일을 추가하는 중복코드가 사라졌습니다 
- 판매글 목록을 가져오는 모든 기능에서 썸네일 이미지 추가 기능이 필요한 상황입니당. 그런데 관심목록을 가져오는 기능은 판매글 관심 서비스에 위치하다보니, 판매글 서비스에 존재하는 썸네일 추가 기능을 사용하지 못해 중복 코드가 발생합니다
- EM-77
=> ♻️  refactor : 관심목록 받아올 때 이미지 경로도 함께 가져오기 리팩토링

src/main/java/com/devcourse/eggmarket/domain/model/image/ImageFile.java, src/main/java/com/devcourse/eggmarket/domain/model/image/PostImageFile.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/main/java/com/devcourse/eggmarket/domain/user/controller/UserController.java, src/main/java/com/devcourse/eggmarket/domain/user/service/DefaultUserService.java, src/main/java/com/devcourse/eggmarket/domain/user/service/UserService.java, src/test/java/com/devcourse/eggmarket/domain/user/controller/UserControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/user/service/DefaultUserServiceTest.java
- 이미지 업로드 로직 변경
- 프로필 이미지 업로드 로직을 비동기화하였습니다. 회원 가입의 경우에는 프로필 이미지는 저장 실패하더라도 회원가입 처리 되는 것이 중요하기 때문입니다.
- 이 때, 실패시 로그를 출력해주고 싶어도, 비동기 로직이 실행되는 스레드에서 발생하는 예외는 ControllerAdvice 에서 처리할 수 없습니다
- 따라서 UserService 계층에서 로거를 통해 로그를 출력하도록 하였습니다 (어떻게 깔끔하게 할지 모르겠습니다..)
- 포스트 이미지 업로드 로직 변경 :
이런 상황이었습니다.
- ![image](https://user-images.githubusercontent.com/53856184/177326858-88c976dc-d0db-4f0b-930a-bf281dbbc27e.png)
value 에 아무것도 전달하지 않았다고 생각했는데, 멀티파트 구현체가 전달되어오는 상황이었습니다. 사실상 포스트 이미지를 등록하지 않은 상황으로 볼 수 있기 때문에, 이 경우에는 포스트 작성이 실패해서는 안됨에도 불구하고, 로직상 실패하고 있었습니다. 
- 따라서 이를 해결하기 위해 필터링 로직을 추가하였습니다 ( fix 커밋이었어야 했겠네요 ㅠ-ㅠ)
- 회원가입시 Long 타입을 반환하는 것으로 변경하였습니다.
- 다른 엔티티들과 마찬가지로 , 새로운 엔티티를 생성하여 저장할 경우 Long 타입 반환으로 변경하였습니다. 
- save 결과가 Long 타입으로 변경되다보니 기존 테스트들이 유효하지 않아 이를 변경하였습니다. 
- EM-78
=> ✨  feat : 이미지 업로드 로직 변경 

src/main/asciidoc/post-api.adoc, src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/model/Post.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- 판매글을 제목을 기준으로 검색할 수 있도록 기능 추가
- `/search?word=title` 와 같은 형태로 사용
- 판매글 검색 기능 테스트 코드 추가
- EM-25
=> ✨ feat : 판매글 검색 기능 추가

src/main/asciidoc/user-api.adoc, src/main/java/com/devcourse/eggmarket/domain/user/controller/UserController.java, src/main/java/com/devcourse/eggmarket/domain/user/converter/UserConverter.java, src/main/java/com/devcourse/eggmarket/domain/user/dto/UserRequest.java, src/main/java/com/devcourse/eggmarket/domain/user/dto/UserResponse.java, src/main/java/com/devcourse/eggmarket/domain/user/service/DefaultUserService.java, src/main/java/com/devcourse/eggmarket/domain/user/service/UserService.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/ImageStub.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java, src/test/java/com/devcourse/eggmarket/domain/stub/UserStub.java, src/test/java/com/devcourse/eggmarket/domain/user/controller/UserControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/user/converter/UserConverterTest.java, src/test/java/com/devcourse/eggmarket/domain/user/service/DefaultUserServiceTest.java
- 프로필 이미지는 POST `/users/profile/image` 로 변경 (이미지 업로드에 사용하는 multipart/form-data가 GET, POST 지원)
- 유저 정보 변경은 PUT `/users/profile` 로 변경
- userConverter 테스트 코드 추가
- 유저 업데이트시 id 값만 반환하도록 변경
- 컨트롤러 테스트 추가 및 수정
- EM-14
=>  ♻️ refactor : 업로드 유저 프로필 이미지 변경과 유저 정보 변경 분리 및 구현

src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/main/resources/schema.sql, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java
- 판매글 삭제시 이미지도 삭제되는 로직을 추가했습니다
- DDL 의 참조관계가 잘못되어있어 수정했습니다
- EM-84
=> ✨  feat : 판매글 삭제시 이미지도 삭제되는 로직 추가

src/main/resources/application-test.yaml, src/test/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/comment/service/CommentServiceIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/user/controller/UserControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/user/service/DefaultUserServiceTest.java
- 서버의 DB 드라이버, url, username, password와 같은 민감정보는 서버측의 환경변수로 저장
- 통합테스트의 경우 `@ActiveProfile`을 이용하여 테스트용 프로파일로 동작하도록 변경
- EM-47
=> 🔧 config : 서버용 프로파일 수정 및 테스트용 프로파일 생성
