pom.xml, src/main/java/com/devcourse/eggmarket/domain/model/BaseEntity.java, src/main/java/com/devcourse/eggmarket/global/config/JpaAuditingConfig.java, src/test/java/com/devcourse/eggmarket/model/BaseEntityTest.java
- Entity에 공통적으로 포함될 BaseEntity 구현
- BaseEntity Test Code 작성
- BaseEntity JpaAuditingConfig 환경 설정 구현
- pom.xml spring-boot-starter-validation 의존성 추가
- pom.xml h2 database version flyway와의 호환성을 위해 2.1.210으로 변경
- [EM-54](https://hkasdasdq.atlassian.net/browse/EM-54)
=> ✨ feat : BaseEntity 기능 구현

src/main/java/com/devcourse/eggmarket/domain/user/dto/UserRequest.java, src/main/java/com/devcourse/eggmarket/domain/user/dto/UserResponse.java, src/main/java/com/devcourse/eggmarket/domain/user/model/User.java, src/main/java/com/devcourse/eggmarket/domain/user/model/UserRole.java, src/main/java/com/devcourse/eggmarket/domain/user/model/Users.java, src/main/java/com/devcourse/eggmarket/domain/user/repository/UserRepository.java, src/main/java/com/devcourse/eggmarket/domain/user/service/UserService.java, src/test/java/com/devcourse/eggmarket/model/BaseEntityTest.java
- User Entity 생성 완료
- User Repository Interface 기본 틀 생성 완료
- User Service Interface 기본 메소드 포함해서 생성 완료
- User와 관련된 Request, Response 생성 완료
- EM-52
=> ✨ feat : User Entity 관련 기본 설정 완료

src/main/java/com/devcourse/eggmarket/domain/model/image/PostImage.java, src/main/java/com/devcourse/eggmarket/domain/model/image/exception/InvalidFileException.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostRequest.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/AlreadyCompletedException.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/NotExistBuyerException.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/PostExceptionMessage.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/PurchaseInfoException.java, src/main/java/com/devcourse/eggmarket/domain/post/model/Category.java, src/main/java/com/devcourse/eggmarket/domain/post/model/Post.java, src/main/java/com/devcourse/eggmarket/domain/post/model/PostStatus.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/global/error/GlobalExceptionHandler.java
- [style : code indent 4로 변경](https://github.com/prgrms-be-devcourse/BEDV2_Egg-market/commit/2453e4aa9705f84c5ad98598b49cb213dc0e3ecd)
- [refactor : ControllerAdvice, RestControllerAdvice로 변경](https://github.com/prgrms-be-devcourse/BEDV2_Egg-market/commit/c72545503c90112db8bfc28c7aa0491b8bfe1da9)
- post 및 image exception 계층화
- EM-60
=> Em-60 post 및 image exception 계층화

src/main/java/com/devcourse/eggmarket/domain/user/controller/UserController.java, src/main/java/com/devcourse/eggmarket/domain/user/converter/UserConverter.java, src/main/java/com/devcourse/eggmarket/domain/user/dto/UserRequest.java, src/main/java/com/devcourse/eggmarket/domain/user/dto/UserResponse.java, src/main/java/com/devcourse/eggmarket/domain/user/service/DefaultUserService.java, src/main/java/com/devcourse/eggmarket/domain/user/service/UserService.java, src/main/java/com/devcourse/eggmarket/global/config/WebSecurityConfiguration.java, src/main/resources/application-local.yaml, src/test/java/com/devcourse/eggmarket/domain/user/service/DefaultUserServiceTest.java
- User Login 구현
- User Service : getUser(String userName) 메소드를 통해 username으로 user 객체를 찾아올 수 있습니다.
- EM-9
- User Controller Test 같은 경우, Service에서는 잘 통과하던 부분에서 오류가 나서 일단 커밋하지 않았습니다
=> ✨ feat : 로그인 구현 완료

.gitignore, pom.xml, src/main/java/com/devcourse/eggmarket/global/config/WebSecurityConfiguration.java
- 로그아웃 구현 -> Spring Security에서 제공해주는 logout을 그대로 사용했습니다! /logout을 통해 접근할 수 있습니다.
- EM-10
=> ✨ feat : 로그아웃 구현 완료

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java
- 판매글 ID를 받아 해당 판매글을 삭제하는 기능 추가
현재 로그인 사용자가 판매글 작성자와 다를 경우 예외 발생시키도록 구현
- [EM-20](https://hkasdasdq.atlassian.net/browse/EM-20)
- 테스트 코드 작성은 차후에 하겠습니다
=> ✨ feat : 판매글 삭제 기능 추가

src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- 서비스 계층 판매글 생성  테스트 작성
- EM-18
- 컨트롤러 테스트 WebMVC 설정 문제로 테스트 실패
=> 🧪 test : 판매글 생성 테스트 코드 작성

pom.xml, src/main/java/com/devcourse/eggmarket/EggmarketApplication.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/api/EvaluationController.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/converter/EvaluationConverter.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/dto/EvaluationRequest.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/dto/EvaluationResponse.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/exception/InvalidScoreException.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/model/Evaluation.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/model/Score.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/repository/EvaluationRepository.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/service/EvaluationService.java, src/main/java/com/devcourse/eggmarket/domain/user/controller/UserController.java, src/main/java/com/devcourse/eggmarket/domain/user/dto/UserResponse.java, src/main/java/com/devcourse/eggmarket/domain/user/exception/NotExistUserException.java, src/main/java/com/devcourse/eggmarket/domain/user/model/User.java, src/main/java/com/devcourse/eggmarket/domain/user/repository/UserRepository.java, src/main/java/com/devcourse/eggmarket/domain/user/service/DefaultUserService.java, src/main/java/com/devcourse/eggmarket/domain/user/service/UserService.java, src/main/java/com/devcourse/eggmarket/global/error/GlobalExceptionHandler.java, src/main/java/com/devcourse/eggmarket/global/error/exception/EntityNotFoundException.java, src/main/java/com/devcourse/eggmarket/global/error/exception/ErrorCode.java, src/test/java/com/devcourse/eggmarket/domain/model/BaseEntityTest.java, src/test/java/com/devcourse/eggmarket/domain/post/model/PostTest.java
- [✨ feat : evaluation 기능 구현](https://github.com/prgrms-be-devcourse/BEDV2_Egg-market/commit/ec1f4b62a0d9d848ba93974dd37e317b000bfbbf) 
- evaluationService에서 userService를 가져와 user의 매너 온도를 업데이트 합니다.
- evaluation에서는 Score 정책에 따른 매너 온도를 계산하며, comment가 적혀져 있는 review를 관리합니다.  
- [✨feat : User Not Exist Exception 구현](https://github.com/prgrms-be-devcourse/BEDV2_Egg-market/commit/daf9228be31107dc24fbdac111becc05e7c6285d)
- user 관련 예외 추가
- [EM-30](https://hkasdasdq.atlassian.net/jira/software/projects/EM/boards/3?selectedIssue=EM-30)
=> ✨ feat : evaluation 기능 구현 

src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/UserStub.java
- 판매글 업데이트와 상태 업데이트에 대한 테스트 서비스 계층 테스트 코드 추가
- EM-19
=> 🧪 test : 판매글 업데이트 테스트 코드 작성

src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java
- 서비스 계층 판매글 테스트 삭제 테스트 추가
- EM-20
=> 🧪 test : 판매글 삭제 테스트 추가

src/main/java/com/devcourse/eggmarket/domain/comment/api/CommentController.java, src/main/java/com/devcourse/eggmarket/domain/comment/converter/CommentConverter.java, src/main/java/com/devcourse/eggmarket/domain/comment/dto/CommentRequest.java, src/main/java/com/devcourse/eggmarket/domain/comment/exception/CommentNotAllowedPostException.java, src/main/java/com/devcourse/eggmarket/domain/comment/model/Comment.java, src/main/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepository.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/CommentService.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/DefaultCommentService.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/main/java/com/devcourse/eggmarket/domain/post/model/Post.java, src/main/java/com/devcourse/eggmarket/domain/post/service/DefaultPostAttentionService.java, src/main/java/com/devcourse/eggmarket/global/error/exception/ErrorCode.java, src/test/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/comment/service/CommentServiceIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostRepositoryTest.java
- Comment 엔티티 , 레포지토리, 서비스, 엔티티 추가
- 댓글 작성 기능, 컨트롤러 구현
- CommentRepository 와 댓글 서비스에 대한 테스트 코드 작성 
- Postconverter 의 todo 구현
- CommentNotAllowedPostException 과 이에 대한 ErrorCode 추가
- EM-26
=> ✨ feat: 댓글 엔티티 정의 및 댓글 작성기능 추가

src/main/resources/logback.xml
- 기본적으로 INFO 레벨로 로그를 찍도록 구현
- STDOUT, 파일로 INFO 레벨이 찍히면 ERROR 레벨로 찍힌 로그의 경우 별도의 로그 파일로 관리하도록 구현
- EM-50
=> 🔧 config : logback 설정

src/main/java/com/devcourse/eggmarket/global/aop/CommonPointcut.java, src/main/java/com/devcourse/eggmarket/global/aop/LoggingAspect.java
- Controller, Service, Repository 계층간 이동시 어떤 메서드에 접근했고 어떤 값을 반환했는지 로깅
- EM-40
=> ✨ feat : AOP를 이용한 계층별 로깅 적용

src/main/java/com/devcourse/eggmarket/domain/evaluation/api/EvaluationController.java, src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostResponse.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/main/java/com/devcourse/eggmarket/global/common/SuccessResponse.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceImplTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java
- restdocs에서 Long 타입이 반환되지 않는 문제로 응답시 추가적으로 응답객체를 만들어 반환하도록 수정
- user와 comment는 conflict 때문에 나중에 수정예정
- EM-71
=> ♻️ refactor : 성공시 응답객체를 만들어 반환

src/main/java/com/devcourse/eggmarket/domain/comment/api/CommentController.java, src/main/java/com/devcourse/eggmarket/domain/comment/dto/CommentRequest.java, src/main/java/com/devcourse/eggmarket/domain/comment/dto/CommentResponse.java, src/main/java/com/devcourse/eggmarket/domain/comment/exception/CommentNotAllowedPostException.java, src/main/java/com/devcourse/eggmarket/domain/comment/exception/NotExistCommentException.java, src/main/java/com/devcourse/eggmarket/domain/comment/exception/NotWriterException.java, src/main/java/com/devcourse/eggmarket/domain/comment/model/Comment.java, src/main/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepository.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/CommentService.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/DefaultCommentService.java, src/main/java/com/devcourse/eggmarket/global/error/exception/ErrorCode.java, src/test/java/com/devcourse/eggmarket/domain/comment/repository/CommentRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/comment/service/CommentServiceIntegrationTest.java
- posts/postdId/comments/commentId 로 댓글 수정을 요청할 수 있습니다
- 댓글 수정 기능 로직을 구현
- CommentResponse 에 Comments, CommentsElement 추가
- ErrorCode 에 커멘트 관련 에러 추가 ( 커멘트작성자가 아닌 경우에 대한 권한 에러, 존재하지 않는 커멘트에 대한 예외 추가 )
SuccessResponse 사용하는 것으로 변경하겠습니다 
- EM-27
=> ✨  feat : 댓글 수정 기능 및 테스트 구현

src/main/asciidoc/post-api.adoc, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java
- 판매글 찜하기 컨트롤러 테스트 추가
- 찜하기 기능 restdocs 작성
- EM-32
=> 🧪 test : 판매글 찜하기 테스트 추가

src/main/asciidoc/post-api.adoc, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java
- 찜한 판매글 조회기능 컨트롤러 테스트 추가
- restdocs 추가
- EM-17
=> 🧪 test : 찜한 판매글 조회 기능 테스트 코드 추가

src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java
- id를 equals로 비교하던 방식에서 User의 isSameUser를 사용하도록 변경
- 이슈 : EM-19
=> ♻️ refactor : 현재 로그인 유저가 판매자(작성자)인지 확인하는 로직 리팩토링

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/dto/PostRequest.java, src/main/java/com/devcourse/eggmarket/domain/post/exception/PostExceptionMessage.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/main/java/com/devcourse/eggmarket/global/error/ErrorField.java, src/main/java/com/devcourse/eggmarket/global/error/GlobalExceptionHandler.java, src/main/java/com/devcourse/eggmarket/global/error/exception/ErrorCode.java
- 언제부턴가 PostController 의 모든 메소드가 public 이 아닌 default(private-package) 로 되어있어 이를 public 으로 변경하였습니다
- 포스트는 이미지 개수를 10개 이하로 받고, 이미지 용량 제한도 걸어야 하는데, 다른 방식이 떠오르지 않네요
-  1. DTO 검증조건으로 파일 개수 제한을 걸었고 -> 이로 인해, rejectedValue 메시지를 깔끔하게 만들기 위한 코드를 ErrorCode 에 추가. 2. 파일 용량과 관련한 에러핸들링을 GlobalException 에서 다루는 방식으로 작성. 
- EM-80
=> ✨  feat : 포스트 이미지 개수 검증조건 추가 및 용량에 대한 에러처리

src/main/java/com/devcourse/eggmarket/domain/post/repository/PostRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java
- 전체조회시 List로 반환하도록 변경하여 DB 쿼리 최소화
- EM-24, EM-25
=> ♻️ refactor : Repository 에서 판매글 조회 반환시 Page가 아닌 List 형태로 반환하도록 수정

src/main/java/com/devcourse/eggmarket/domain/post/api/PostController.java, src/main/java/com/devcourse/eggmarket/domain/post/repository/PostRepository.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostService.java, src/main/java/com/devcourse/eggmarket/domain/post/service/PostServiceImpl.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/post/repository/PostRepositoryTest.java, src/test/java/com/devcourse/eggmarket/domain/post/service/PostServiceIntegrationTest.java
- 기존에는 모든 목록을 가져오던 것 -> 커서기반 페이징 구현으로 최신순 목록을 가져오는 것으로 변경
- EM-81
=> ✨ feat : 관심목록 가져오기 기능을 페이징 기반 구현으로 변경

src/main/asciidoc/comment-api.adoc, src/main/java/com/devcourse/eggmarket/domain/comment/api/CommentController.java, src/main/java/com/devcourse/eggmarket/domain/comment/service/DefaultCommentService.java, src/main/java/com/devcourse/eggmarket/domain/model/image/PostImageFile.java, src/main/java/com/devcourse/eggmarket/domain/post/converter/PostConverter.java, src/test/java/com/devcourse/eggmarket/domain/comment/api/CommentControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/comment/converter/CommentConverterTest.java, src/test/java/com/devcourse/eggmarket/domain/post/converter/PostConverterTest.java, src/test/java/com/devcourse/eggmarket/domain/user/controller/UserControllerTest.java
- 댓글 관련 restdocs 추가
- 커멘트 컨트롤러에 대한 정상적인 상황에 대한 테스트 
- DTO 실패상황 테스트 
- 커멘트 작성시 전달되는 Location header 에 잘못된 uri 정보가 전달되고 있어 이를 수정함
- EM-82
=> 🧪  test: CommentControllerTest 추가 

src/main/asciidoc/eval-api.adoc, src/main/java/com/devcourse/eggmarket/domain/evaluation/api/EvaluationController.java, src/main/java/com/devcourse/eggmarket/domain/evaluation/service/EvaluationService.java, src/test/java/com/devcourse/eggmarket/domain/evaluation/api/EvaluationControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/evaluation/service/EvaluationServiceTest.java
- 🧪 test : 평가 도메인 테스트 작성(https://github.com/prgrms-be-devcourse/BEDV2_Egg-market/pull/63/commits/4b951b57b60bb9f45bdf7614781f40b7f33b1b30)
-  📝 docs : api 문서 작성(https://github.com/prgrms-be-devcourse/BEDV2_Egg-market/commit/03878df6bbf521a99462fa06e114c79db0bb1203)
-  ♻️ refactor : controlelr 수정(https://github.com/prgrms-be-devcourse/BEDV2_Egg-market/commit/b17ee5c3fb1173e099de1ac9c760b1ac697ac6e1)
현재 Service에 private method를 사용하는 부분 mocking이 조금 잘 못 된 거 같아 수정 예정입니다!
- EM-79
=> 🧪 test : 평가 도메인 테스트 작성

src/main/asciidoc/post-api.adoc, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerIntegrationTest.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/stub/ImageStub.java, src/test/java/com/devcourse/eggmarket/domain/stub/PostStub.java, src/test/java/com/devcourse/eggmarket/domain/stub/UserStub.java, src/test/java/com/devcourse/eggmarket/domain/user/service/DefaultUserServiceTest.java
- Post 통합테스트 작성
- restdocs path parameter도 보이도록 적용
- EM-83
- 판매글 상태 변경시 다른 유저로 댓글을 달아야하는데 로그인 유저를 테스트 중에 어떻게 바꿀지 모르겠습니다. 일단 해당 테스트는 Disabled 했습니다
=> 🧪 test : Post 통합테스트 작성 및 restdocs 수정

scripts/start.sh
- 배포시 prod 프로파일로 실행되도록 설정
-  EM-41
=> 🔧 config : 배포시 prod 프로파일로 실행되도록 설정

src/main/resources/application-prod.yaml
- 배포시 sql 초기화하지 않도록 변경
- EM-47
=> 🔧 config : 배포시 sql 초기화하지 않도록 변경

src/main/asciidoc/comment-api.adoc, src/main/asciidoc/user-api.adoc, src/test/java/com/devcourse/eggmarket/domain/comment/api/CommentControllerTest.java, src/test/java/com/devcourse/eggmarket/domain/post/api/PostControllerTest.java
- comment 댓글작성 request body 안보이던 문제 수정
- post 검색기능 누락된 것 추가
- user-api 유저 찾기, 유저 간단 조회 누락된 것 추가
-  EM-87
=> 🐛 fix : 현재 표시 되지 않는 restdocs 문서 수정
